#
#   Super RISC-V - superscalar dual-issue RISC-V processor
#   Copyright (C) 2024-2026 Dominik Salvet
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# ACCEPTED MACROS:
#   ASSERTS=1           enable SV assertions
#   MAX_CYCLES=<value>  max cycles of simulation (0 - no limit)
#   TEST_GROUP=<group>  selected group of tests
#   TEST_NAME=<name>    test to be run on the CPU
#   SIM_OUT_DIR=<path>  directory for all files generated by simulation
#   X_VAL=0|1|2         unknown values in SV are replaced with:
#                       0 - zeros, 1 - ones, 2 - random values
#   SEED=<value>        seed used for any randomized event
#   INPUT_IN_FILE=1     use input file of respective test as stdin
#                       e.g., TEST_NAME=foo -> stdin=foo_input.txt
#                       if not existing, empty file is used instead

RTL_DIR = rtl
TB_DIR = tb
TESTS_DIR = tests
UTILS_DIR = utils

# out directory is used for generated files
OUT_DIR = out
BUILD_DIR = $(OUT_DIR)/build
OUT_TESTS_DIR = $(OUT_DIR)/tests

# TODO: consider support for other simulators (free, student editions, ...)
VERILATOR = verilator
GTKWAVE = gtkwave

# RISC-V GCC tools
RV_AS = riscv64-unknown-elf-as
RV_LD = riscv64-unknown-elf-ld
RV_GCC = riscv64-unknown-elf-gcc
RV_OBJCOPY = riscv64-unknown-elf-objcopy
RV_OBJDUMP = riscv64-unknown-elf-objdump
RV_READELF = riscv64-unknown-elf-readelf
RV_SIZE = riscv64-unknown-elf-size

RV_GCC_FLAGS = -march=rv32i -mabi=ilp32 -mstrict-align
# RV_OBJDUMP_FLAGS = -M numeric,no-aliases
# RV_OBJDUMP_FLAGS = --source -l

# Newlib standard C library
NEWLIB_INCLUDE ?= /opt/newlib/riscv64-unknown-elf/include
NEWLIB_LIB ?= /opt/newlib/riscv64-unknown-elf/lib

SRC_FILES = $(RTL_DIR)/pkg/riscv_types_pkg.sv\
            $(RTL_DIR)/pkg/srv_types_pkg.sv\
            $(TB_DIR)/pkg/exec_trace_pkg.sv\
            $(RTL_DIR)/super_riscv.sv\
            $(RTL_DIR)/ifu/ifu.sv\
            $(RTL_DIR)/ifu/ifb.sv\
            $(RTL_DIR)/dec/dec.sv\
            $(RTL_DIR)/dec/inst_dec.sv\
            $(RTL_DIR)/dec/gpr.sv\
            $(RTL_DIR)/dec/fwd_init.sv\
            $(RTL_DIR)/exu/exu.sv\
            $(RTL_DIR)/exu/alu.sv\
            $(RTL_DIR)/exu/bru.sv\
            $(RTL_DIR)/lsu.sv\
            $(TB_DIR)/tb.sv\
            $(TB_DIR)/ahb_mem.sv

TOP_MODULE = tb
# wrapper is used by verilator-generated makefile (hence absolute path)
CPP_WRAPPER = $(abspath $(TB_DIR)/$(TOP_MODULE)_wrapper.cpp)
TOP_CLASS = V$(TOP_MODULE)

# TODO: start testing using third-party test suites
# TODO: add support for popular benchmarks
# supported test group names
TEST_GROUPS = simple_asm\
              simple_c\
              simple_libc

# process accepted macros
TEST_GROUP ?= simple_asm
TEST_NAME ?= hello_world
SIM_OUT_DIR ?= $(OUT_DIR)
X_VAL ?= 0

TEST_BUILD_DIR = $(OUT_TESTS_DIR)/$(TEST_GROUP)
TEST_PREFIX = $(TEST_BUILD_DIR)/$(TEST_NAME)
RET_VAL_FILE = $(SIM_OUT_DIR)/ret_val.txt
WAVES_FILE = $(SIM_OUT_DIR)/waves.fst
TRACE_FILE = $(SIM_OUT_DIR)/trace.log
EXEC_FLAGS =

# prepare execution flags for CPU simulator
ifneq ($(ASSERTS), 1)
    EXEC_FLAGS += +verilator+noassert
endif
ifdef MAX_CYCLES
    EXEC_FLAGS += +max+cycles=$(MAX_CYCLES)
endif
EXEC_FLAGS += +verilator+rand+reset+$(X_VAL)
ifdef SEED
    EXEC_FLAGS += +verilator+seed+$(SEED)
endif
EXEC_FLAGS += +test+path=$(TEST_PREFIX).hex
EXEC_FLAGS += +ret+val+file=$(RET_VAL_FILE)

# extra arguments for building tests (programs)
TEST_BUILD_ARGS = \
    RV_AS=$(RV_AS) \
    RV_LD=$(RV_LD) \
    RV_GCC=$(RV_GCC) \
    RV_GCC_FLAGS='$(RV_GCC_FLAGS)' \
    NEWLIB_INCLUDE=$(NEWLIB_INCLUDE) \
    NEWLIB_LIB=$(NEWLIB_LIB) \
    TESTS_DIR=$(abspath $(TESTS_DIR)) \
    TEST_BUILD_DIR=$(abspath $(TEST_BUILD_DIR)) \
    TEST_NAME=$(TEST_NAME)

# lint and transform RTL to C++ in default (quick check)
verilate: $(BUILD_DIR)_verilated
build: $(BUILD_DIR)/$(TOP_CLASS)

$(BUILD_DIR):
	mkdir -p $@

$(BUILD_DIR)_verilated: $(SRC_FILES) | $(BUILD_DIR)
	$(VERILATOR) --cc --exe -Wall -Wno-fatal --top-module $(TOP_MODULE)\
          --assert\
          --trace-fst --trace-structs\
          --x-assign unique --x-initial unique\
          -Mdir $(BUILD_DIR)\
          -DEXEC_TRACE_SUPPORT\
          $^ $(CPP_WRAPPER)
	touch $@

$(BUILD_DIR)/$(TOP_CLASS): $(CPP_WRAPPER) $(BUILD_DIR)_verilated
	$(MAKE) -j -C $(BUILD_DIR) -f $(TOP_CLASS).mk

# this target uses a precompiled program and ignores user macros
hello_world: $(BUILD_DIR)/$(TOP_CLASS) $(UTILS_DIR)/hello_world.hex
	./$< +verilator+noassert +verilator+rand+reset+0 +test+path=$(UTILS_DIR)/hello_world.hex +ret+val+file=$(OUT_DIR)/ret_val.txt

# this rule must be executed even when target exists
FORCE:
$(TEST_PREFIX): FORCE
	$(MAKE) -C $(TESTS_DIR)/$(TEST_GROUP) $(TEST_BUILD_ARGS)

$(TEST_PREFIX).hex: $(TEST_PREFIX)
	$(RV_OBJCOPY) -O verilog $< $@
	chmod -x $@

$(TEST_PREFIX).dis: $(TEST_PREFIX)
	$(RV_OBJDUMP) $(RV_OBJDUMP_FLAGS) -d $< > $@.tmp
	mv $@.tmp $@

$(TEST_PREFIX)_info.txt: $(TEST_PREFIX)
	$(RV_READELF) -a $< > $@.tmp
	mv $@.tmp $@

# compose simulation rules
SIM_PREREQ := $(BUILD_DIR)/$(TOP_CLASS) $(TEST_PREFIX).hex
DEBUG_PREREQ := $(SIM_PREREQ) $(TEST_PREFIX) $(TEST_PREFIX).dis $(TEST_PREFIX)_info.txt
EXEC_RECIPE := ./$(BUILD_DIR)/$(TOP_CLASS) $(EXEC_FLAGS)
ifeq ($(INPUT_IN_FILE), 1)
    SIM_PREREQ += $(OUT_TESTS_DIR)/input_copy.txt
    DEBUG_PREREQ += $(OUT_TESTS_DIR)/input_copy.txt
    EXEC_RECIPE += < $(OUT_TESTS_DIR)/input_copy.txt
endif

$(OUT_TESTS_DIR)/input_copy.txt: FORCE
	cp $(TESTS_DIR)/$(TEST_GROUP)/$(TEST_NAME)_input.txt $@ 2>/dev/null || true > $@

$(SIM_OUT_DIR):
	mkdir -p $@

sim: $(SIM_PREREQ) | $(SIM_OUT_DIR)
	$(EXEC_RECIPE)
	read -r ret_val_var < $(RET_VAL_FILE) && test "$$ret_val_var" = 0

# when generating debug info, simulation is allowed to fail
debug: $(DEBUG_PREREQ) | $(SIM_OUT_DIR)
	$(RV_SIZE) -G $(TEST_PREFIX)
	rm -f $(RET_VAL_FILE)
	-$(EXEC_RECIPE) +waves +waves+file=$(WAVES_FILE) +trace +trace+file=$(TRACE_FILE)
	test -f $(RET_VAL_FILE)

open_waves:
	@test -f $(WAVES_FILE) || { echo "First use 'debug' target to generate '$(WAVES_FILE)' file."; false; }
	$(GTKWAVE) $(WAVES_FILE) $(UTILS_DIR)/config.gtkw

print_test_groups:
	@echo $(TEST_GROUPS) | tr ' ' '\n'

print_test_names:
	@$(MAKE) -C $(TESTS_DIR)/$(TEST_GROUP) --no-print-directory $@

clean:
	if [ -d $(OUT_DIR) ]; then rm -r $(OUT_DIR); fi

clean_tests:
	if [ -d $(OUT_TESTS_DIR) ]; then rm -r $(OUT_TESTS_DIR); fi
