#
#   Super RISC-V - superscalar dual-issue RISC-V processor
#   Copyright (C) 2025-2026 Dominik Salvet
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

name: Run Tests
on: [push, pull_request]

jobs:
  Testing:
    runs-on: ubuntu-latest
    container:
      image: dominiksalvet/super-riscv-env:v1.1

    steps:
    - name: Checkout commit
      uses: actions/checkout@v7

    - name: Verilate design
      run: make verilate

    - name: Build design
      run: make build

    - name: Run Hello World
      run: make hello_world

    - name: Run testing workload
      run: ./run_workload.sh ci_testing

# TODO: update this once workload runner finished
    # - name: Upload testing report
    #   uses: actions/upload-artifact@v4
    #   if: always()
    #   with:
    #     name: run_tests_report
    #     path: out/run_tests.log
